In [1]:
import numpy as np
import pandas as pd
from bokeh.io import show, output_file
from bokeh.palettes import Spectral5
from bokeh.plotting import figure
from bokeh.sampledata.autompg import autompg as df
from bokeh.transform import factor_cmap

In [13]:
strikes = pd.read_csv('AfghanistanUSAFdata_ weapons released.csv', skiprows=2)
strikes.columns = strikes.iloc[0]
#strikes = strikes.rename(columns={'nan': 'year'})
strikes = strikes.drop(0)

In [15]:
strikes.fillna(0)

,nan,January,February,March,April,May,June,July,August,September,October,November,December,Total,Year-on-year change in total weapons released,Weapons released per month,Year-on-year change in weapons released per month
1,2010.0,156,154,175,197,300,457,325,416,739,"1,043",866,272,5100,-,425,-
2,2011.0,405,341,337,339,426,610,695,516,597,663,308,174,5411,6.10%,451,6.10%
3,2012.0,170,116,227,252,406,521,504,589,385,414,297,202,4083,-24.54%,340,-24.54%
4,2013.0,193,297,250,284,368,337,256,158,232,189,118,76,2758,-32.45%,230,-32.45%
5,2014.0,92,114,95,115,164,272,205,437,441,217,87,126,2365,-14.25%,197,-14.25%
6,2015.0,40,30,47,31,41,109,79,156,111,203,69,31,947,-59.96%,79,-59.96%
7,2016.0,127,115,58,62,89,94,160,108,162,205,92,65,1337,41.18%,111,41.18%
8,2017.0,54,200,203,460,328,389,350,503,414,653,352,455,4361,226.18%,363,226.18%
9,2018.0,378,469,396,562,591,572,746,715,841,0,0,0,5213,0,579,0